### PR TITLE
Motion Controls

### PR DESCRIPTION
**Pull request by Poohl**
This implements a shake-to-roll gesture.

Shake sensitivity is the on also used for shake-wake. There is hysteresis to prevent it from rolling too often due to shaking and to prevent it from rolling twice from the shaking due to tapping the screen. The display disable timer is reset when rolled like this, even when the display is already off (because shake wake is enabled to detect the shake gesture).

Thanks to @vincentbeer for helping with this.

### CODE REVIEW

**Comment by yusufmte** [comment]
This is amazing, thanks for implementing / adding this feature!! Definitely adds a nice flavor to the rolling. I'll take a look and merge it in with this one later this week.

**Comment by yusufmte** [comment]
@Poohl Have you had this working in testing? No build errors but it isn't working for me in testing on the PineTime (no response to shaking whether shake-wake is on or not) -- I can't immediately find why skimming the code, but haven't had a chance to comb through it more thoroughly yet. Any ideas?

**Comment by Poohl** [comment]
Yes, I've been running this just fine for the last week on my Pinetime.
See if the shake-calibration is set. (open the shake-calibration screen in the settings and pull the slider somewhere/calibrate it).

Also a test you can do:
* Open the dice
* wait until the screen turns off  (completely off, not jut dimmed)
* shake
  * If the screen turns on it should also roll the dice. 
  * If the screen doesn't turn on something else is broken. 
  * If the screen turns on but it's not rolling, there is some issue in my code.

Also be aware that after flashing with these modifications sometimes I had to go into the settings and readjust everything, not really a clue why. I assumed it's something to do with memory layouts changing due to extra code.

**Comment by yusufmte** [comment]
Sorry, I haven't have a chance to test till now! It is working very well just like you said, after re-flashing-- I think the mistake was on my end and I may have flashed the wrong DFU/firmware after building.

I really like the feature. Really enhances the "dice" feel and the roll hysteresis is nicely tuned. The code looks good as well. Nice job and thanks again for making this! Merging into this branch/PR.

**Pull request merged**
